Models/Auditory.cs
namespace BNTU_fond.Models
{
    public class Auditory
    {
        public int AuditoryId { get; set; }
        public int FloorId { get; set; }
        public int AuditoryNum { get; set; }
        public int? Places { get; set; }
        public int? Computers { get; set; }
    }
}

Models/Building.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace BNTU_fond.Models
{
    public class Building
    {
        public int BuildingId { get; set; }
        public string Name { get; set; }
    }
}

Models/Floor.cs
namespace BNTU_fond.Models
{
    public class Floor
    {
        public int FloorId { get; set; }
        public int BuildingId { get; set; }
        public int FloorNum { get; set; }
    }
}

Models/ViewModel/AuditoryViewModel.cs
using System.Collections.Generic;
using System.Linq;

namespace BNTU_fond.Models.ViewModel
{
    public class AuditoryViewModel
    {
        public int FloorNum { get; set; }
        public int FloorId { get; set; }
        public int BuildingId { get; set; }
        public IQueryable<Auditory> Auditories { get; set; }
    }
}

Controllers/AuditoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BNTU_fond.Models;
using BNTU_fond.Models.ViewModel;
using BNTU_fond.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BNTU_fond.Controllers
{
    public class AuditoryController : Controller
    {
        private readonly IRepository<Auditory> auditoryRepo;
        private readonly IRepository<Floor> floorRepo;

        public AuditoryController(IRepository<Auditory> auditoryRepo, IRepository<Floor> floorRepo)
        {
            this.auditoryRepo = auditoryRepo;
            this.floorRepo = floorRepo;
        }

        public IActionResult Index(int id)
        {
            var auditoryViewModel = new AuditoryViewModel();
            var auditories = auditoryRepo.GetAll().Where(auditory => auditory.FloorId == id);

            auditoryViewModel.Auditories = auditories;
            auditoryViewModel.FloorId = id;
            auditoryViewModel.FloorNum = floorRepo.GetById(id).FloorNum;
            auditoryViewModel.BuildingId = floorRepo.GetById(id).BuildingId;

            return View(auditoryViewModel);
        }

        public IActionResult Create(int id)
        {
            ViewBag.FloorId = id;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(int id, Auditory auditory)
        {
            if (ModelState.IsValid)
            {
                auditory.FloorId = id;
                auditoryRepo.Create(auditory);

                return RedirectToAction("Index", new { id });
            }

            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var auditory = auditoryRepo.GetById(id);

            if (auditory == null)
            {
                return new StatusCodeResult(404);
            }

            return View(auditory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Auditory auditory)
        {
            auditoryRepo.Update(auditory);

            return RedirectToAction("Index", new { id = auditory.FloorId });
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var auditory = auditoryRepo.GetById(id);

            if (auditory == null)
            {
                return new StatusCodeResult(404);
            }

            return View(auditory);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            var auditory = auditoryRepo.GetById(id);

            auditoryRepo.Delete(auditory);

            return RedirectToAction("Index", new { id = auditory.FloorId });
        }
    }
}

Controllers/BuildingController.cs
using BNTU_fond.Models;
using BNTU_fond.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BNTU_fond.Controllers
{
    public class BuildingController : Controller
    {
        private readonly IRepository<Building> buildingRepo;

        public BuildingController(IRepository<Building> buildingRepo)
        {
            this.buildingRepo = buildingRepo;
        }

        public IActionResult Index()
        {
            var building = buildingRepo.GetAll();

            return View(building);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Building building)
        {
            if (ModelState.IsValid)
            {
                buildingRepo.Create(building);

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var building = buildingRepo.GetById(id);

            if (building == null)
            {
                return new StatusCodeResult(404);
            }

            return View(building);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Building building)
        {
            buildingRepo.Update(building);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var building = buildingRepo.GetById(id);

            if (building == null)
            {
                return new StatusCodeResult(404);
            }

            return View(building);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            var building = buildingRepo.GetById(id);

            buildingRepo.Delete(building);

            return RedirectToAction("Index");
        }
    }
}

Controllers/FloorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BNTU_fond.Models;
using BNTU_fond.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BNTU_fond.Controllers
{
    public class FloorController : Controller
    {
        private readonly IRepository<Floor> floorRepo;

        public FloorController(IRepository<Floor> floorRepo)
        {
            this.floorRepo = floorRepo;
        }

        public IActionResult Index(int id)
        {
            ViewBag.BuildingId = id;
            var floors = floorRepo.GetAll().Where(floor => floor.BuildingId == id);

            return View(floors);
        }

        public IActionResult Create(int id)
        {
            ViewBag.BuildingId = id;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(int id, Floor floor)
        {
            if (ModelState.IsValid)
            {
                floor.BuildingId = id;
                floorRepo.Create(floor);

                return RedirectToAction("Index", new { id });
            }

            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var floor = floorRepo.GetById(id);

            if (floor == null)
            {
                return new StatusCodeResult(404);
            }

            return View(floor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Floor floor)
        {
            floorRepo.Update(floor);

            return RedirectToAction("Index", new { id = floor.BuildingId });
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var floor = floorRepo.GetById(id);

            if (floor == null)
            {
                return new StatusCodeResult(404);
            }

            return View(floor);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            var floor = floorRepo.GetById(id);

            floorRepo.Delete(floor);

            return RedirectToAction("Index", new { id = floor.BuildingId });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BNTU_fond.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Auditory/Create.cshtml
@model BNTU_fond.Models.Auditory
@{
    ViewBag.Title = "Add auditory";
}

<div class="header">
    <h2>Add auditory</h2>
</div>

@using (Html.BeginForm())
{
    <div class="body">
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.AuditoryNum, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.AuditoryNum, new { htmlAttributes = new { @class = "form-control", required = "required" }, style = "width: 100%" })
                @Html.ValidationMessageFor(model => model.AuditoryNum, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Places, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Places, new { htmlAttributes = new { @class = "form-control", required = "required" }, style = "width: 100%" })
                @Html.ValidationMessageFor(model => model.Places, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Computers, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Computers, new { htmlAttributes = new { @class = "form-control", required = "required" }, style = "width: 100%" })
                @Html.ValidationMessageFor(model => model.Computers, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="d-flex justify-content-between">
            <input type="submit" value="Save" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index", "Auditory", new { id = ViewBag.FloorId }, new { @class = "btn btn-light" })
        </div>
    </div>
}

Views/Auditory/Delete.cshtml
@model BNTU_fond.Models.Auditory
@{
    ViewBag.Title = "Delete auditory";
}

<div class="header text-center">
    <h2>Are you sure you want to delete this auditory "@Model.AuditoryNum" ?</h2>
</div>

@using (Html.BeginForm())
{
    <div class="body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.FloorId)

        <div class="d-flex justify-content-between">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Back to List", "Index", "Auditory", new { id = Model.FloorId }, new { @class = "btn btn-light" })
        </div>
    </div>
}

Views/Auditory/Edit.cshtml
@model BNTU_fond.Models.Auditory
@{
    ViewBag.Title = "Edit auditory";
}

<div class="header">
    <h2>Edit auditory №@Model.AuditoryNum</h2>
</div>

@using (Html.BeginForm())
{
    <div class="body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.AuditoryId)
        @Html.HiddenFor(model => model.FloorId)

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.AuditoryNum, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.AuditoryNum, new { htmlAttributes = new { @class = "form-control", required = "required" }, style = "width: 100%" })
                @Html.ValidationMessageFor(model => model.AuditoryNum, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Places, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Places, new { htmlAttributes = new { @class = "form-control", required = "required" }, style = "width: 100%" })
                @Html.ValidationMessageFor(model => model.Places, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Computers, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Computers, new { htmlAttributes = new { @class = "form-control", required = "required" }, style = "width: 100%" })
                @Html.ValidationMessageFor(model => model.Computers, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="d-flex justify-content-between">
            <input type="submit" value="Save" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index", "Auditory", new { id = Model.FloorId }, new { @class = "btn btn-light" })
        </div>
    </div>
}

Views/Auditory/Index.cshtml
@model BNTU_fond.Models.ViewModel.AuditoryViewModel


@{
    ViewBag.Title = $"Аuditories on the {Model.FloorNum} floor";
}

<h2>Аuditories on the @Model.FloorNum floor</h2>

<p>
    @Html.ActionLink("Add auditory", "Create", null, new { id = Model.FloorId }, new { @class = "btn btn-success" })
</p>

<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                Auditory number
            </th>
            <th scope="col">
                Places
            </th>
            <th scope="col">
                Computers
            </th>
            <th scope="col">
                Actions
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.Auditories)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AuditoryNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Places)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Computers)
            </td>
            <td class="d-flex justify-content-around">
                <div class="btn-group-vertical">
                    @Html.ActionLink("Edit", "Edit", new { id = item.AuditoryId }, new { @class = "btn btn-success" })
                </div>
                <div class="btn-group-vertical">
                    @Html.ActionLink("Delete", "Delete", new { id = item.AuditoryId }, new { @class = "btn btn-danger" })
                </div>
            </td>
        </tr>
        }
    </tbody>
</table>
<div class="d-flex justify-content-around">
    @Html.ActionLink("Back to floors page", "Index", "Floor", new { id = Model.BuildingId }, new { @class = "btn btn-light" })
</div>

Views/Building/Create.cshtml
@model BNTU_fond.Models.Building
@{
    ViewBag.Title = "Add building";
}

<div class="header">
    <h2>Add building</h2>
</div>

@using (Html.BeginForm())
{
    <div class="body">
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", required = "required" }, style = "width: 100%" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="d-flex justify-content-between">
            <input type="submit" value="Save" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index", "Building", null, new { @class = "btn btn-light" })
        </div>
    </div>
}

Views/Building/Delete.cshtml
@model BNTU_fond.Models.Building
@{
    ViewBag.Title = "Delete building";
}

<div class="header text-center">
    <h2>Are you sure you want to delete this building "@Model.Name" ?</h2>
</div>

@using (Html.BeginForm())
{
    <div class="body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.BuildingId)

        <div class="d-flex justify-content-between">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Back to List", "Index", "Building", null, new { @class = "btn btn-light" })
        </div>
    </div>
}

Views/Building/Edit.cshtml
@model BNTU_fond.Models.Building
@{
    ViewBag.Title = "Edit building";
}

<div class="header">
    <h2>Edit "@Model.Name" building</h2>
</div>

@using (Html.BeginForm())
{
    <div class="body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.BuildingId)

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", required = "required" }, style = "width: 100%" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="d-flex justify-content-between">
            <input type="submit" value="Save" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index", "Building", null, new { @class = "btn btn-light" })
        </div>
    </div>
}

Views/Building/Index.cshtml
@model IQueryable<BNTU_fond.Models.Building>


@{
    ViewBag.Title = "Buildings";
}

<h2>Buildings list</h2>

<p>
    @Html.ActionLink("Add building", "Create", null, null, new { @class = "btn btn-success" })
</p>

<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                Id
            </th>
            <th scope="col">
                Name
            </th>
            <th scope="col">
                Actions
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BuildingId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td class="d-flex justify-content-around">
                <div class="btn-group-vertical">
                    @Html.ActionLink("Edit", "Edit", new { id = item.BuildingId }, new { @class = "btn btn-success" })
                </div>
                <div class="btn-group-vertical">
                    @Html.ActionLink("Delete", "Delete", new { id = item.BuildingId }, new { @class = "btn btn-danger" })
                </div>
                <div class="btn-group-vertical">
                    @Html.ActionLink("Floors", "Index", "Floor", new { id = item.BuildingId }, new { @class = "btn btn-info" })
                </div>

            </td>
        </tr>
        }
    </tbody>
</table>

Views/Floor/Create.cshtml
@model BNTU_fond.Models.Floor
@{
    ViewBag.Title = "Add floor";
}

<div class="header">
    <h2>Add floor</h2>
</div>

@using (Html.BeginForm())
{
<div class="body">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.FloorNum, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.FloorNum, new { htmlAttributes = new { @class = "form-control", required = "required" }, style = "width: 100%" })
            @Html.ValidationMessageFor(model => model.FloorNum, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="d-flex justify-content-between">
        <input type="submit" value="Save" class="btn btn-success" />
        @Html.ActionLink("Back to List", "Index", "Floor", new { id = ViewBag.BuildingId }, new { @class = "btn btn-light" })
    </div>
</div>
}

Views/Floor/Delete.cshtml
@model BNTU_fond.Models.Floor
@{
    ViewBag.Title = "Delete floor";
}

<div class="header text-center">
    <h2>Are you sure you want to delete this floor №"@Model.FloorNum" ?</h2>
</div>

@using (Html.BeginForm())
{
    <div class="body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.FloorId)

        <div class="d-flex justify-content-between">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Back to List", "Index", "Floor", new { id = Model.BuildingId }, new { @class = "btn btn-light" })
        </div>
    </div>
}

Views/Floor/Edit.cshtml
@model BNTU_fond.Models.Floor
@{
    ViewBag.Title = "Edit floor";
}

<div class="header">
    <h2>Edit floor №"@Model.FloorNum"</h2>
</div>

@using (Html.BeginForm())
{
    <div class="body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.FloorId)
        @Html.HiddenFor(model => model.BuildingId)

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.FloorNum, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.FloorNum, new { htmlAttributes = new { @class = "form-control", required = "required" }, style = "width: 100%" })
                @Html.ValidationMessageFor(model => model.FloorNum, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="d-flex justify-content-between">
            <input type="submit" value="Save" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index", "Floor", new { id = Model.BuildingId }, new { @class = "btn btn-light" })
        </div>
    </div>
}

Views/Floor/Index.cshtml
@model IQueryable<BNTU_fond.Models.Floor>


@{
    ViewBag.Title = "Floors building №" + ViewBag.BuildingId;
}

    <h2>Floors building №@ViewBag.BuildingId</h2>

<p>
    @Html.ActionLink("Add floor", "Create", null, new { id = ViewBag.BuildingId }, new { @class = "btn btn-success" })
</p>

<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                Floor number
            </th>
            <th scope="col">
                Actions
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FloorNum)
            </td>
            <td class="d-flex justify-content-around">
                <div class="btn-group-vertical">
                    @Html.ActionLink("Edit", "Edit", new { id = item.FloorId }, new { @class = "btn btn-success" })
                </div>
                <div class="btn-group-vertical">
                    @Html.ActionLink("Delete", "Delete", new { id = item.FloorId }, new { @class = "btn btn-danger" })
                </div>
                <div class="btn-group-vertical">
                    @Html.ActionLink("Auditories", "Index", "Auditory", new { id = item.FloorId }, new { @class = "btn btn-info" })
                </div>

            </td>
        </tr>
        }
    </tbody>
</table>
<div class="d-flex justify-content-around">
    @Html.ActionLink("Back to buildings page", "Index", "Building", null, new { @class = "btn btn-light" })
</div>

Views/Home/Index.cshtml
Hello BNTU!

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/node_modules/bootstrap/dist/css/bootstrap.css" />
    <title>@ViewBag.Title</title>
</head>
<body class="d-flex flex-column h-100">

    <main role="main" class="flex-shrink-0">
        <div class="container">
            @RenderBody()
        </div>
    </main>

    <footer class="footer mt-auto py-3">
        <div class="container">
            <span class="text-white">&copy; @DateTime.Now.Year - Roman Litvin</span>
        </div>
    </footer>

    @RenderSection("scripts", required: false)
</body>
</html>